apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: tasky-admin
      containers:
        - name: tasky
          image: proton69/cicd:1.2
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: "mongodb://muser:%21Pa%24%24w0rd%21@ec2-52-37-75-46.us-west-2.compute.amazonaws.com:27017/admin"
            - name: SECRET_KEY
              value: "W1lQQByyX++eZneYmPrVdooSQaTF15Vx8C+iYHH+30Y="
---
apiVersion: v1
kind: Service
metadata:
  name: tasky
spec:
  selector:
    app: tasky
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
